# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IgMvyTCE1VMIv4zSaUhcN43Wg1Eqt1fp
"""

print("Hola Mundo");